# Generated by Django 5.0.2 on 2024-02-25 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=240, verbose_name='Name')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20, verbose_name='Password')),
                ('role', models.CharField(default='user', max_length=20, verbose_name='Role')),
                ('refreshToken', models.CharField(max_length=40, verbose_name='RefreshToken')),
                ('createdDate', models.DateField(auto_now_add=True, verbose_name='CreatedDate')),
            ],
        ),
    ]
