# Generated by Django 5.0.2 on 2024-02-25 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_student_user'),
    ]

    operations = [
    ]
