# Generated by Django 5.0.2 on 2024-02-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='refreshToken',
            field=models.CharField(max_length=40, null=True, verbose_name='RefreshToken'),
        ),
    ]
